name: parallel-queues

services:
  rabbitmq:
    image: masstransit/rabbitmq:4.0.2
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP port
    command: rabbitmq-plugins enable rabbitmq_management

  ordering:
    build:
      context: ../src
      dockerfile: WiredBrain.Ordering/Dockerfile
    depends_on:
      - rabbitmq

  billing:
    build:
      context: ../src
      dockerfile: WiredBrain.Billing/Dockerfile
    depends_on:
      - rabbitmq

  shipping:
    build:
      context: ../src
      dockerfile: WiredBrain.Shipping/Dockerfile
    depends_on:
      - rabbitmq

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
