name: parallel-queues

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 512M

  ordering:
    build:
      context: ../src
      dockerfile: WiredBrain.Ordering/Dockerfile
    ports:
      - "8081:80"
    environment:
      - ORDER_ARRIVAL_RATE_MS=1000
    depends_on:
      - rabbitmq

  billing:
    build:
      context: ../src
      dockerfile: WiredBrain.Billing/Dockerfile
    environment:
      - BILLING_PROCESSING_DELAY_MS=200
    ports:
      - "8082:80"  # Expose port for metrics scraping
    depends_on:
      - rabbitmq

  shipping:
    build:
      context: ../src
      dockerfile: WiredBrain.Shipping/Dockerfile
    depends_on:
      - rabbitmq

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
